package openclaw

import (
	"fmt"
	"strings"

	"github.com/mostlydev/clawdapus/internal/driver"
)

// GenerateClawdapusMD builds the CLAWDAPUS.md context file — the infrastructure
// layer's letter to the agent. Contains identity, surfaces, and skill index.
// Injected into the agent's context via bootstrap-extra-files hook.
func GenerateClawdapusMD(rc *driver.ResolvedClaw, podName string) string {
	var b strings.Builder

	b.WriteString("# CLAWDAPUS.md\n\n")
	b.WriteString("This file is generated by Clawdapus. It describes your infrastructure environment.\n\n")

	// Identity
	b.WriteString("## Identity\n\n")
	b.WriteString(fmt.Sprintf("- **Pod:** %s\n", podName))
	b.WriteString(fmt.Sprintf("- **Service:** %s\n", rc.ServiceName))
	b.WriteString(fmt.Sprintf("- **Type:** %s\n", rc.ClawType))
	b.WriteString("\n")

	// Surfaces
	b.WriteString("## Surfaces\n\n")
	if len(rc.Surfaces) == 0 {
		b.WriteString("No surfaces declared for this service.\n\n")
	} else {
		for _, s := range rc.Surfaces {
			b.WriteString(fmt.Sprintf("### %s (%s)\n", s.Target, s.Scheme))
			if s.AccessMode != "" {
				b.WriteString(fmt.Sprintf("- **Access:** %s\n", s.AccessMode))
			}
			switch s.Scheme {
			case "volume":
				b.WriteString(fmt.Sprintf("- **Mount path:** /mnt/%s\n", s.Target))
			case "service":
				b.WriteString(fmt.Sprintf("- **Host:** %s\n", s.Target))
			case "channel":
			}
			b.WriteString("\n")
		}
	}

	// Skills index
	b.WriteString("## Skills\n\n")
	var skillEntries []string

	// Explicit operator skills
	for _, sk := range rc.Skills {
		skillEntries = append(skillEntries, fmt.Sprintf("- `skills/%s` — operator-provided skill", sk.Name))
	}

	if len(skillEntries) == 0 {
		b.WriteString("No skills available.\n")
	} else {
		for _, entry := range skillEntries {
			b.WriteString(entry + "\n")
		}
	}

	return b.String()
}
