x-claw:
  pod: trading-desk

# ─────────────────────────────────────────────────────────────────────────────
# Trading Desk Pod (minimal: tiverton + westin)
#
# Two isolated openclaw agents coordinating via Discord and a shared research
# volume. Each agent runs its own openclaw instance in its own container.
#
# Required environment variables (.env or Docker secrets):
#   POSTGRES_PASSWORD, SECRET_KEY_BASE
#   TIVERTON_BOT_TOKEN, WESTIN_BOT_TOKEN
#   TIVERTON_DISCORD_ID, WESTIN_DISCORD_ID
#   DISCORD_GUILD_ID, DISCORD_TRADING_FLOOR_CHANNEL
#   OPENROUTER_API_KEY (proxy-side provider key for cllama)
# ─────────────────────────────────────────────────────────────────────────────

services:

  # ── Infrastructure (non-claw) ──────────────────────────────────────────────

  postgres:
    image: postgres:16-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_DB: trading_api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  trading-api:
    image: trading-api:latest
    expose:
      - "4000"
    environment:
      PYTHONUNBUFFERED: "1"
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/trading_api_development"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      # Webhook URL for startup announcements — no bot token needed for a non-claw service.
      # CLAW_HANDLE_* vars (agent Discord IDs) are broadcast automatically by claw.
      DISCORD_TRADING_API_WEBHOOK: "${DISCORD_TRADING_API_WEBHOOK}"
    depends_on:
      - postgres

  # ── Tiverton — Coordinator, Compliance, News Synthesis ────────────────────

  tiverton:
    image: trading-desk:latest
    build:
      context: .
      dockerfile: Clawfile
    x-claw:
      agent: ./agents/TIVERTON.md
      cllama: passthrough
      # Provider keys for cllama only. These never enter agent service env.
      cllama-env:
        OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
        ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      handles:
        discord:
          id: "${TIVERTON_DISCORD_ID}"
          username: "tiverton"
          guilds:
            - id: "${DISCORD_GUILD_ID}"
              name: "Trading Floor"
              channels:
                - id: "${DISCORD_TRADING_FLOOR_CHANNEL}"
                  name: trading-floor
      surfaces:
        - "service://trading-api"
        - "volume://clawd-shared read-write"
        - channel://discord:
            dm:
              enabled: true
              policy: allowlist
              allow_from:
                - "${OPERATOR_DISCORD_ID}"
      skills:
        - ./policy/risk-limits.md
        - ./policy/approval-workflow.md
      invoke:
        - schedule: "15 8 * * 1-5"
          name: "Pre-market synthesis"
          message: "Pre-market synthesis. Write report to /mnt/clawd-shared/reports/morning/$(date +%Y-%m-%d)-tiverton.md and post summary to #trading-floor."
          to: trading-floor
        - schedule: "*/30 * * * *"
          name: "Heartbeat"
          message: "Post a brief status update to #trading-floor."
          to: trading-floor
    environment:
      DISCORD_BOT_TOKEN: "${TIVERTON_BOT_TOKEN}"
      CLAW_GREETING_CHANNEL: "${DISCORD_TRADING_FLOOR_CHANNEL}"
      CLAW_GREETING_MESSAGE: "tiverton online."

  # ── Westin — Momentum / Tech Stocks ──────────────────────────────────────

  westin:
    image: trading-desk:latest
    build:
      context: .
      dockerfile: Clawfile
    x-claw:
      agent: ./agents/WESTIN.md
      cllama: passthrough
      handles:
        discord:
          id: "${WESTIN_DISCORD_ID}"
          username: "westin"
          guilds:
            - id: "${DISCORD_GUILD_ID}"
              name: "Trading Floor"
              channels:
                - id: "${DISCORD_TRADING_FLOOR_CHANNEL}"
                  name: trading-floor
      surfaces:
        - "service://trading-api"
        - "volume://clawd-shared read-write"
      skills:
        - ./policy/risk-limits.md
      invoke:
        - schedule: "0 * * * *"
          name: "Momentum check"
          message: "Scan momentum signals for top tech holdings. Post any high-conviction moves to #trading-floor."
          to: trading-floor
    environment:
      DISCORD_BOT_TOKEN: "${WESTIN_BOT_TOKEN}"
      CLAW_GREETING_CHANNEL: "${DISCORD_TRADING_FLOOR_CHANNEL}"
      CLAW_GREETING_MESSAGE: "westin online."
