package clawctl

import "github.com/mostlydev/clawdapus/internal/driver"

// PodManifest is the runtime topology snapshot consumed by the clawctl dashboard.
// It is generated by `claw up` before compose materialization.
type PodManifest struct {
	PodName  string                     `json:"podName"`
	Services map[string]ServiceManifest `json:"services"`
	Proxies  []ProxyManifest            `json:"proxies,omitempty"`
}

type ServiceManifest struct {
	ClawType    string                                   `json:"clawType,omitempty"`
	ImageRef    string                                   `json:"imageRef"`
	Agent       string                                   `json:"agent,omitempty"`
	Models      map[string]string                        `json:"models,omitempty"`
	Count       int                                      `json:"count"`
	Handles     map[string]*driver.HandleInfo            `json:"handles,omitempty"`
	PeerHandles map[string]map[string]*driver.HandleInfo `json:"peerHandles,omitempty"`
	Surfaces    []SurfaceManifest                        `json:"surfaces,omitempty"`
	Skills      []string                                 `json:"skills,omitempty"`
	Invocations []driver.Invocation                      `json:"invocations,omitempty"`
	Cllama      []string                                 `json:"cllama,omitempty"`
}

type SurfaceManifest struct {
	Scheme        string                `json:"scheme"`
	Target        string                `json:"target"`
	AccessMode    string                `json:"accessMode,omitempty"`
	Ports         []string              `json:"ports,omitempty"`
	ChannelConfig *driver.ChannelConfig `json:"channelConfig,omitempty"`
}

type ProxyManifest struct {
	ProxyType   string `json:"proxyType"`
	ServiceName string `json:"serviceName"`
	Image       string `json:"image"`
}
