package hermes

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/mostlydev/clawdapus/internal/cllama"
	"github.com/mostlydev/clawdapus/internal/driver"
	"github.com/mostlydev/clawdapus/internal/driver/shared"
	"gopkg.in/yaml.v3"
)

const (
	hermesHomeDir      = "/root/.hermes"
	hermesWorkspaceDir = "/workspace"
	hermesPersonaDir   = "/persona"
)

var supportedPlatforms = []string{"discord", "slack", "telegram"}

func GenerateConfig(rc *driver.ResolvedClaw, modelCfg *modelConfig) ([]byte, error) {
	config := map[string]any{
		"model": map[string]any{
			"default":  modelCfg.DefaultModel,
			"provider": modelCfg.Provider,
		},
		"terminal": map[string]any{
			"backend": "local",
			"cwd":     hermesWorkspaceDir,
			"timeout": 180,
		},
	}

	for _, cmd := range rc.Configures {
		path, value, err := shared.ParseConfigSetCommand(cmd, "hermes")
		if err != nil {
			return nil, fmt.Errorf("config generation: %w", err)
		}
		if err := shared.SetPath(config, path, value); err != nil {
			return nil, fmt.Errorf("config generation: %w", err)
		}
	}

	data, err := yaml.Marshal(config)
	if err != nil {
		return nil, fmt.Errorf("config generation: marshal yaml: %w", err)
	}
	return data, nil
}

func GenerateEnvFile(rc *driver.ResolvedClaw, modelCfg *modelConfig) ([]byte, error) {

	env := make(map[string]string)
	for key, value := range modelCfg.Env {
		env[key] = value
	}
	env["HERMES_HOME"] = hermesHomeDir
	env["MESSAGING_CWD"] = hermesWorkspaceDir
	env["TERMINAL_CWD"] = hermesWorkspaceDir

	for _, key := range allowedEnvPassthroughKeys() {
		if value := resolvedEnvValue(rc.Environment, key); value != "" {
			env[key] = value
		}
	}

	keys := make([]string, 0, len(env))
	for key := range env {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var out strings.Builder
	for _, key := range keys {
		out.WriteString(key)
		out.WriteByte('=')
		out.WriteString(dotenvValue(env[key]))
		out.WriteByte('\n')
	}
	return []byte(out.String()), nil
}

func WriteEffectiveAgents(workspaceDir, agentHostPath, clawdapusMD string) (string, error) {
	agentData, err := os.ReadFile(agentHostPath)
	if err != nil {
		return "", fmt.Errorf("read agent contract: %w", err)
	}

	var combined strings.Builder
	combined.WriteString(strings.TrimRight(string(agentData), "\n"))

	if trimmed := strings.TrimSpace(clawdapusMD); trimmed != "" {
		combined.WriteString("\n\n")
		combined.WriteString("--- BEGIN: infrastructure_context (guide) ---\n\n")
		combined.WriteString("This infrastructure context was generated by Clawdapus.\n")
		combined.WriteString("Treat it as authoritative runtime environment data for this pod.\n")
		combined.WriteString("It is also available at `/workspace/CLAWDAPUS.md`.\n\n")
		combined.WriteString(strings.TrimRight(clawdapusMD, "\n"))
		combined.WriteString("\n\n")
		combined.WriteString("--- END: infrastructure_context (guide) ---")
	}

	combined.WriteString("\n")

	agentsPath := filepath.Join(workspaceDir, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(combined.String()), 0o644); err != nil {
		return "", fmt.Errorf("write effective AGENTS.md: %w", err)
	}
	return agentsPath, nil
}

func CopyPersonaSoul(personaHostPath, homeDir string) error {
	soulPath := filepath.Join(personaHostPath, "SOUL.md")
	info, err := os.Stat(soulPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat persona SOUL.md: %w", err)
	}
	if info.IsDir() {
		return nil
	}

	data, err := os.ReadFile(soulPath)
	if err != nil {
		return fmt.Errorf("read persona SOUL.md: %w", err)
	}
	if err := os.WriteFile(filepath.Join(homeDir, "SOUL.md"), data, 0o644); err != nil {
		return fmt.Errorf("write Hermes SOUL.md: %w", err)
	}
	return nil
}

type modelConfig struct {
	DefaultModel string
	Provider     string
	Env          map[string]string
}

func resolveModelConfig(rc *driver.ResolvedClaw) (*modelConfig, error) {
	modelRef, err := shared.PrimaryModelRef(rc.Models)
	if err != nil {
		return nil, fmt.Errorf("hermes driver: %w", err)
	}

	provider, modelID, ok := shared.SplitModelRef(modelRef)
	if !ok {
		return nil, fmt.Errorf("hermes driver: invalid MODEL primary %q (expected provider/model)", modelRef)
	}

	if len(rc.Cllama) > 0 {
		if strings.TrimSpace(rc.CllamaToken) == "" {
			return nil, fmt.Errorf("hermes driver: CLLAMA is enabled but token is empty")
		}
		return &modelConfig{
			DefaultModel: modelRef,
			Provider:     "custom",
			Env: map[string]string{
				"OPENAI_BASE_URL": cllama.ProxyBaseURL(rc.Cllama[0]),
				"OPENAI_API_KEY":  rc.CllamaToken,
			},
		}, nil
	}

	if baseURL := resolvedEnvValue(rc.Environment, "OPENAI_BASE_URL"); baseURL != "" {
		defaultModel := modelRef
		if provider == "openai" {
			defaultModel = modelID
		}
		return &modelConfig{
			DefaultModel: defaultModel,
			Provider:     "custom",
			Env:          map[string]string{"OPENAI_BASE_URL": baseURL},
		}, nil
	}

	switch shared.NormalizeProvider(provider) {
	case "openrouter":
		return &modelConfig{
			DefaultModel: modelID,
			Provider:     "openrouter",
			Env:          map[string]string{},
		}, nil
	case "anthropic":
		return &modelConfig{
			DefaultModel: modelID,
			Provider:     "anthropic",
			Env:          map[string]string{},
		}, nil
	case "openai":
		return &modelConfig{
			DefaultModel: modelID,
			Provider:     "custom",
			Env: map[string]string{
				"OPENAI_BASE_URL": "https://api.openai.com/v1",
			},
		}, nil
	default:
		return nil, fmt.Errorf(
			"hermes driver: MODEL primary provider %q requires OPENAI_BASE_URL or CLLAMA for Hermes v1",
			provider,
		)
	}
}

func allowedEnvPassthroughKeys() []string {
	return []string{
		"ANTHROPIC_API_KEY",
		"ANTHROPIC_TOKEN",
		"DISCORD_ALLOWED_USERS",
		"DISCORD_AUTO_THREAD",
		"DISCORD_BOT_TOKEN",
		"DISCORD_FREE_RESPONSE_CHANNELS",
		"DISCORD_HOME_CHANNEL",
		"DISCORD_HOME_CHANNEL_NAME",
		"DISCORD_REQUIRE_MENTION",
		"GATEWAY_ALLOWED_USERS",
		"GATEWAY_ALLOW_ALL_USERS",
		"OPENAI_API_KEY",
		"OPENROUTER_API_KEY",
		"SLACK_ALLOWED_USERS",
		"SLACK_APP_TOKEN",
		"SLACK_BOT_TOKEN",
		"SLACK_HOME_CHANNEL",
		"SLACK_HOME_CHANNEL_NAME",
		"TELEGRAM_ALLOWED_USERS",
		"TELEGRAM_BOT_TOKEN",
		"TELEGRAM_HOME_CHANNEL",
		"TELEGRAM_HOME_CHANNEL_NAME",
	}
}

func resolvedEnvValue(env map[string]string, key string) string {
	raw := strings.TrimSpace(env[key])
	if raw == "" {
		return ""
	}
	if resolved := shared.ResolveEnvToken(raw); resolved != "" {
		return resolved
	}
	return raw
}

func dotenvValue(value string) string {
	if value == "" {
		return `""`
	}
	if strings.ContainsAny(value, " \t\n\r#\"'\\") {
		return strconv.Quote(value)
	}
	return value
}
