package shared

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mostlydev/clawdapus/internal/driver"
)

// GenerateClawdapusMD builds the CLAWDAPUS.md context file — the infrastructure
// layer's letter to the agent. Contains identity, surfaces, and skill index.
// Injected into the agent's context via bootstrap-extra-files hook.
func GenerateClawdapusMD(rc *driver.ResolvedClaw, podName string) string {
	var b strings.Builder

	b.WriteString("# CLAWDAPUS.md\n\n")
	b.WriteString("This file is generated by Clawdapus. It describes your infrastructure environment.\n\n")

	// Identity
	b.WriteString("## Identity\n\n")
	b.WriteString(fmt.Sprintf("- **Pod:** %s\n", podName))
	b.WriteString(fmt.Sprintf("- **Service:** %s\n", rc.ServiceName))
	b.WriteString(fmt.Sprintf("- **Type:** %s\n", rc.ClawType))
	if rc.Persona != "" {
		b.WriteString(fmt.Sprintf("- **Persona Ref:** %s\n", rc.Persona))
	}
	b.WriteString("\n")

	if rc.PersonaHostPath != "" {
		b.WriteString("## Persona\n\n")
		b.WriteString("Your mutable persona workspace is mounted separately from the behavioral contract.\n\n")
		b.WriteString("- **Mount:** `persona/`\n")
		if rc.Persona != "" {
			b.WriteString(fmt.Sprintf("- **Source:** `%s`\n", rc.Persona))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Memory\n\n")
	b.WriteString("Your portable cross-driver memory directory is mounted separately from the runner workspace.\n\n")
	b.WriteString(fmt.Sprintf("- **Mount:** `%s`\n", PortableMemoryDir))
	b.WriteString(fmt.Sprintf("- **Env:** `%s`\n", PortableMemoryEnv))
	b.WriteString("- **Shared files:** `MEMORY.md` for durable agent notes, `USER.md` for user-specific preferences\n")
	b.WriteString("- **Working notes:** dated files like `2026-03-26.md` when you need a running log\n")
	b.WriteString("- **Portability:** this directory is intended to survive claw-type changes for the same service\n")
	switch rc.ClawType {
	case "hermes":
		b.WriteString("- **Native alias:** `~/.hermes/memories/` reads and writes the same files\n")
	case "openclaw":
		b.WriteString("- **Native alias:** `/claw/MEMORY.md` resolves to the shared `MEMORY.md` file\n")
	}
	b.WriteString("\n")

	if len(rc.Invocations) > 0 {
		b.WriteString("## Scheduling\n\n")
		b.WriteString("Some scheduled invocations are infrastructure-owned.\n\n")
		b.WriteString("- **Compile-time source:** Clawdapus compiles image and pod INVOKE entries into runner/runtime artifacts during `claw up`.\n")
		if rc.ClawType == "openclaw" {
			b.WriteString("- **Wake authority:** pod-origin schedules are fired by `claw-api`, not by relying on OpenClaw's own cron timing.\n")
			b.WriteString("- **Do not treat native cron as durable state:** runner-native cron entries you create yourself may conflict with infrastructure-owned schedules and can be overwritten by the next `claw up`.\n")
		}
		b.WriteString("- **Operator rule:** if a new recurring task should persist, add it to the pod or image definition instead of creating it ad hoc inside the runner.\n\n")
	}

	// Surfaces
	b.WriteString("## Surfaces\n\n")
	if len(rc.Surfaces) == 0 {
		b.WriteString("No surfaces declared for this service.\n\n")
	} else {
		for _, s := range rc.Surfaces {
			b.WriteString(fmt.Sprintf("### %s (%s)\n", s.Target, s.Scheme))
			if s.AccessMode != "" {
				b.WriteString(fmt.Sprintf("- **Access:** %s\n", s.AccessMode))
			}
			switch s.Scheme {
			case "volume":
				b.WriteString(fmt.Sprintf("- **Mount path:** /mnt/%s\n", s.Target))
			case "host":
				b.WriteString(fmt.Sprintf("- **Mount path:** %s\n", s.Target))
			case "service":
				b.WriteString(fmt.Sprintf("- **Host:** %s\n", s.Target))
				if len(s.Ports) > 0 {
					b.WriteString(fmt.Sprintf("- **Ports:** %s\n", strings.Join(s.Ports, ", ")))
				}
				if s.ServiceInfo != nil {
					if s.ServiceInfo.AuthEnv != "" {
						b.WriteString(fmt.Sprintf("- **Auth:** `%s` (%s)\n", s.ServiceInfo.AuthEnv, serviceAuthTypeLabel(s.ServiceInfo.AuthType)))
					}
					if s.ServiceInfo.Description != "" {
						b.WriteString("\n")
						b.WriteString(s.ServiceInfo.Description + "\n")
					}
					if len(s.ServiceInfo.Endpoints) > 0 {
						b.WriteString("\nEndpoints:\n")
						for _, endpoint := range s.ServiceInfo.Endpoints {
							line := fmt.Sprintf("- `%s %s`", endpoint.Method, endpoint.Path)
							if endpoint.Description != "" {
								line += fmt.Sprintf(" — %s", endpoint.Description)
							}
							b.WriteString(line + "\n")
						}
					}
				}
				if s.SkillName != "" {
					b.WriteString(fmt.Sprintf("\nFull service manual: `skills/%s`\n", s.SkillName))
				}
			case "channel":
				if tokenVar := PlatformTokenVar(s.Target); tokenVar != "" {
					b.WriteString(fmt.Sprintf("- **Token:** `%s` (env)\n", tokenVar))
				}
				if s.ChannelConfig != nil {
					for _, line := range renderChannelSurfaceDetails(s.ChannelConfig) {
						b.WriteString(line + "\n")
					}
				}
			}
			b.WriteString("\n")
		}
	}

	if len(rc.Cllama) > 0 {
		b.WriteString("## LLM Proxy\n\n")
		b.WriteString("Your inference is routed through a governance proxy for logging and policy enforcement. Model and endpoint wiring is managed by the harness - leave it alone.\n\n")

		b.WriteString("## Self-history introspection\n\n")
		b.WriteString("You can read your own retained turns through the cllama proxy. Self-scoped: returns only your own history, not pod-wide or cross-agent.\n\n")
		b.WriteString("- **Endpoint:** `$CLAW_SELF_HISTORY_URL/$CLAW_AGENT_ID`\n")
		b.WriteString("- **Auth:** pre-wired (`CLAW_SELF_HISTORY_TOKEN` carries your bearer)\n")
		b.WriteString("- **Pagination:** optional `?after=<RFC3339>` and `?limit=<N>`\n")
		b.WriteString("- **Response:** newline-delimited JSON (`application/x-ndjson`), one retained entry per line in chronological order\n\n")
		b.WriteString("Use this when an operator asks you to explain past behavior or when reasoning over your own session. Don't poll.\n\n")
	}

	// Handles
	if len(rc.Handles) > 0 {
		b.WriteString("## Handles\n\n")
		b.WriteString("Your channel identities on social platforms. Other agents use these to reach you.\n\n")

		// Sort platform names for determinism
		platforms := make([]string, 0, len(rc.Handles))
		for p := range rc.Handles {
			platforms = append(platforms, p)
		}
		sort.Strings(platforms)

		for _, platform := range platforms {
			info := rc.Handles[platform]
			if info == nil {
				continue
			}
			b.WriteString(fmt.Sprintf("### %s\n", platform))
			b.WriteString(fmt.Sprintf("- **ID:** %s\n", info.ID))
			if info.Username != "" {
				b.WriteString(fmt.Sprintf("- **Username:** %s\n", info.Username))
			}
			for _, guild := range info.Guilds {
				guildLine := fmt.Sprintf("- **Guild:** %s", guild.ID)
				if guild.Name != "" {
					guildLine += fmt.Sprintf(" (%s)", guild.Name)
				}
				b.WriteString(guildLine + "\n")
				for _, ch := range guild.Channels {
					chLine := fmt.Sprintf("  - **Channel:** %s", ch.ID)
					if ch.Name != "" {
						chLine += fmt.Sprintf(" (#%s)", ch.Name)
					}
					b.WriteString(chLine + "\n")
				}
			}
			b.WriteString("\n")
		}
	}

	// Communication Tools section — only when handles are configured.
	if len(rc.Handles) > 0 {
		b.WriteString("## Communication Tools\n\n")
		b.WriteString("Your channels are communication tools, not output pipes. ")
		b.WriteString("Think privately. Speak deliberately.\n\n")
		b.WriteString("**Policy:** Your reasoning is always private and never reaches any channel. ")
		b.WriteString("To communicate, call the appropriate tool explicitly. ")
		b.WriteString("If you have nothing meaningful to say, return without calling any tool — silence is correct.\n\n")
	}

	// Peer Handles — sibling services' contact cards so agents can @mention each other
	if len(rc.PeerHandles) > 0 {
		b.WriteString("## Peer Handles\n\n")
		b.WriteString("Other agents in this pod and how to reach them.\n\n")

		// Sort peer service names for determinism
		peerNames := make([]string, 0, len(rc.PeerHandles))
		for pn := range rc.PeerHandles {
			peerNames = append(peerNames, pn)
		}
		sort.Strings(peerNames)

		for _, peerName := range peerNames {
			peerPlatforms := rc.PeerHandles[peerName]
			b.WriteString(fmt.Sprintf("### %s\n", peerName))

			platforms := make([]string, 0, len(peerPlatforms))
			for p := range peerPlatforms {
				platforms = append(platforms, p)
			}
			sort.Strings(platforms)

			for _, platform := range platforms {
				info := peerPlatforms[platform]
				if info == nil {
					continue
				}
				switch platform {
				case "discord":
					// Provide the actual mention syntax — plain @username is just text in Discord.
					b.WriteString(fmt.Sprintf("- **discord:** `<@%s>`", info.ID))
					if info.Username != "" {
						b.WriteString(fmt.Sprintf(" (%s)", info.Username))
					}
				default:
					b.WriteString(fmt.Sprintf("- **%s:** %s", platform, info.ID))
					if info.Username != "" {
						b.WriteString(fmt.Sprintf(" (@%s)", info.Username))
					}
				}
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
	}

	if len(rc.Feeds) > 0 {
		b.WriteString("## Feeds\n\n")
		for _, feed := range rc.Feeds {
			line := fmt.Sprintf("- `%s` from `%s` every %ds", feed.Name, feed.Source, feed.TTL)
			if feed.Path != "" {
				line += fmt.Sprintf(" via `%s`", feed.Path)
			}
			if feed.Description != "" {
				line += fmt.Sprintf(" — %s", feed.Description)
			}
			b.WriteString(line + "\n")
		}
		b.WriteString("\n")
	}

	// Skills index
	b.WriteString("## Skills\n\n")
	var skillEntries []string

	// Mounted service manuals
	for _, s := range rc.Surfaces {
		if s.Scheme == "service" && s.SkillName != "" {
			skillEntries = append(skillEntries, fmt.Sprintf("- `skills/%s` — %s service manual", s.SkillName, s.Target))
		}
	}

	// Operator-provided skills (exclude auto-generated handle-* and surface-* files)
	for _, sk := range rc.Skills {
		if strings.HasPrefix(sk.Name, "handle-") || strings.HasPrefix(sk.Name, "surface-") || strings.HasPrefix(sk.Name, "include-") {
			continue
		}
		skillEntries = append(skillEntries, fmt.Sprintf("- `skills/%s` — operator-provided skill", sk.Name))
	}

	if len(skillEntries) == 0 {
		b.WriteString("No skills available.\n")
	} else {
		for _, entry := range skillEntries {
			b.WriteString(entry + "\n")
		}
	}

	if len(rc.Includes) > 0 {
		b.WriteString("\n## Included Context\n\n")
		for _, include := range rc.Includes {
			b.WriteString(fmt.Sprintf("### %s (%s)\n", include.ID, include.Mode))
			if include.Description != "" {
				b.WriteString(fmt.Sprintf("- **Description:** %s\n", include.Description))
			}
			switch include.Mode {
			case "reference":
				skillPath := "skills/" + include.SkillName
				if include.SkillName == "" {
					skillPath = "skills/"
				}
				b.WriteString(fmt.Sprintf("- **Mount:** `%s`\n", skillPath))
			default:
				b.WriteString("- **Contract:** inlined into `/claw/AGENTS.md`\n")
			}
			b.WriteString(fmt.Sprintf("- **Source:** `%s`\n\n", include.HostPath))
		}
	}

	return b.String()
}

func serviceAuthTypeLabel(authType string) string {
	authType = strings.TrimSpace(authType)
	if authType == "" {
		return "auth"
	}
	return authType
}

func renderChannelSurfaceDetails(cfg *driver.ChannelConfig) []string {
	if cfg == nil {
		return nil
	}

	lines := make([]string, 0)
	if len(cfg.Guilds) > 0 {
		guildIDs := make([]string, 0, len(cfg.Guilds))
		for guildID := range cfg.Guilds {
			guildIDs = append(guildIDs, guildID)
		}
		sort.Strings(guildIDs)
		for _, guildID := range guildIDs {
			guild := cfg.Guilds[guildID]
			line := fmt.Sprintf("- **Guild:** %s", guildID)
			if guild.Policy != "" {
				line += fmt.Sprintf(" (%s)", guild.Policy)
			}
			if guild.RequireMention {
				line += ", mention required"
			}
			lines = append(lines, line)
		}
	}
	if cfg.DM.Enabled || cfg.DM.Policy != "" || len(cfg.DM.AllowFrom) > 0 {
		line := "- **DMs:** "
		if cfg.DM.Enabled {
			line += "enabled"
		} else {
			line += "configured"
		}
		if cfg.DM.Policy != "" {
			line += fmt.Sprintf(" (%s)", cfg.DM.Policy)
		}
		lines = append(lines, line)
	}
	return lines
}
